package com.hunt.game;

import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;

public class Asset {
   public static BufferedImage background;
   public static BufferedImage egg;
   public static BufferedImage life;
   public static BufferedImage plane;
   public static BufferedImage medKit;
   public static BufferedImage gameOver;
   public static BufferedImage gg;
   public static BufferedImage menu;
   public static BufferedImage bunny1_a;
   public static BufferedImage bunny1_b;
   public static BufferedImage bunny1_c;
   public static BufferedImage bunny2_a;
   public static BufferedImage bunny2_b;
   public static BufferedImage bunny2_c;
   public static BufferedImage frog1_a;
   public static BufferedImage frog1_b;
   public static BufferedImage frog2_a;
   public static BufferedImage frog2_b;
   public static BufferedImage pleft_1;
   public static BufferedImage pleft_2;
   public static BufferedImage pleft_3;
   public static BufferedImage pleft_4;
   public static BufferedImage pleft_5;
   public static BufferedImage pleft_6;
   public static BufferedImage pleft_7;
   public static BufferedImage pleft_8;
   public static BufferedImage pleft_9;
   public static BufferedImage pRight_1;
   public static BufferedImage pRight_2;
   public static BufferedImage pRight_3;
   public static BufferedImage pRight_4;
   public static BufferedImage pRight_5;
   public static BufferedImage pRight_6;
   public static BufferedImage pRight_7;
   public static BufferedImage pRight_8;
   public static BufferedImage pRight_9;
   public static BufferedImage puma1;
   public static BufferedImage puma2;
   public static BufferedImage puma3;
   public static BufferedImage puma4;
   public static BufferedImage puma5;
   public static BufferedImage puma6;
   public static BufferedImage puma7;
   public static BufferedImage puma8;
   public static BufferedImage piggy1;
   public static BufferedImage piggy2;
   public static BufferedImage piggy3;
   public static BufferedImage piggy4;
   public static BufferedImage bird1;
   public static BufferedImage bird2;
   public static BufferedImage bird3;
   public static List<BufferedImage> playerSprite;
   public static List<BufferedImage> frogSprite_1;
   public static List<BufferedImage> frogSprite_2;
   public static List<BufferedImage> bunnySprite_1;
   public static List<BufferedImage> bunnySprite_2;
   public static List<BufferedImage> pumaSprite;
   public static List<BufferedImage> piggySprite;
   public static List<BufferedImage> birdSprite;

   public static void init() {
      playerSprite = new ArrayList();
      frogSprite_1 = new ArrayList();
      frogSprite_2 = new ArrayList();
      bunnySprite_1 = new ArrayList();
      bunnySprite_2 = new ArrayList();
      pumaSprite = new ArrayList();
      piggySprite = new ArrayList();
      birdSprite = new ArrayList();
      background = ImageLoader.loadImage("/textures/background.png");
      egg = ImageLoader.loadImage("/textures/egg.png");
      life = ImageLoader.loadImage("/textures/life.png");
      plane = ImageLoader.loadImage("/textures/mediPlane.png");
      medKit = ImageLoader.loadImage("/textures/medKit.png");
      gameOver = ImageLoader.loadImage("/textures/gameOver.png");
      gg = ImageLoader.loadImage("/textures/gg.png");
      menu = ImageLoader.loadImage("/textures/menu.png");
      SpriteSheet sf1 = new SpriteSheet(ImageLoader.loadImage("/textures/frog1.png"));
      SpriteSheet sf2 = new SpriteSheet(ImageLoader.loadImage("/textures/frog2.png"));
      frog1_a = sf1.crop(0, 0, 46, 36);
      frog1_b = sf1.crop(46, 0, 46, 36);
      frog2_a = sf2.crop(0, 0, 47, 35);
      frog2_b = sf2.crop(47, 0, 47, 35);
      SpriteSheet sb1 = new SpriteSheet(ImageLoader.loadImage("/textures/bunny1.png"));
      SpriteSheet sb2 = new SpriteSheet(ImageLoader.loadImage("/textures/bunny2.png"));
      bunny1_a = sb1.crop(0, 0, 30, 26);
      bunny1_b = sb1.crop(30, 0, 30, 26);
      bunny1_c = sb1.crop(60, 0, 30, 26);
      bunny2_a = sb2.crop(0, 0, 31, 28);
      bunny2_b = sb2.crop(31, 0, 31, 28);
      bunny2_c = sb2.crop(62, 0, 31, 28);
      SpriteSheet spa = new SpriteSheet(ImageLoader.loadImage("/textures/puma.png"));
      puma1 = spa.crop(0, 0, 285, 142);
      puma2 = spa.crop(285, 0, 285, 142);
      puma3 = spa.crop(570, 0, 285, 142);
      puma4 = spa.crop(855, 0, 285, 142);
      puma5 = spa.crop(0, 142, 285, 142);
      puma6 = spa.crop(285, 142, 285, 142);
      puma7 = spa.crop(570, 142, 285, 142);
      puma8 = spa.crop(855, 142, 285, 142);
      SpriteSheet spg = new SpriteSheet(ImageLoader.loadImage("/textures/piggy.png"));
      piggy1 = spg.crop(0, 0, 147, 111);
      piggy2 = spg.crop(147, 0, 147, 111);
      piggy3 = spg.crop(294, 0, 147, 111);
      piggy4 = spg.crop(441, 0, 147, 111);
      SpriteSheet sb = new SpriteSheet(ImageLoader.loadImage("/textures/bird.png"));
      bird1 = sb.crop(0, 0, 189, 166);
      bird2 = sb.crop(0, 166, 189, 166);
      bird3 = sb.crop(0, 332, 189, 166);
      SpriteSheet sp = new SpriteSheet(ImageLoader.loadImage("/textures/player.png"));
      pRight_1 = sp.crop(0, 54, 52, 53);
      pRight_2 = sp.crop(52, 54, 52, 53);
      pRight_3 = sp.crop(104, 54, 52, 53);
      pRight_4 = sp.crop(156, 54, 52, 53);
      pRight_5 = sp.crop(208, 54, 52, 53);
      pRight_6 = sp.crop(260, 54, 52, 53);
      pRight_7 = sp.crop(312, 54, 52, 53);
      pRight_8 = sp.crop(364, 54, 52, 53);
      pRight_9 = sp.crop(416, 54, 52, 53);
      pleft_1 = sp.crop(416, 0, 52, 53);
      pleft_2 = sp.crop(364, 0, 52, 53);
      pleft_3 = sp.crop(312, 0, 52, 53);
      pleft_4 = sp.crop(260, 0, 52, 53);
      pleft_5 = sp.crop(208, 0, 52, 53);
      pleft_6 = sp.crop(156, 0, 52, 53);
      pleft_7 = sp.crop(104, 0, 52, 53);
      pleft_8 = sp.crop(52, 0, 52, 53);
      pleft_9 = sp.crop(0, 0, 52, 53);
      addSprite();
   }

   public static void addSprite() {
      playerSprite.add(pRight_1);
      playerSprite.add(pRight_2);
      playerSprite.add(pRight_3);
      playerSprite.add(pRight_4);
      playerSprite.add(pRight_5);
      playerSprite.add(pRight_6);
      playerSprite.add(pRight_7);
      playerSprite.add(pRight_8);
      playerSprite.add(pRight_9);
      playerSprite.add(pleft_1);
      playerSprite.add(pleft_2);
      playerSprite.add(pleft_3);
      playerSprite.add(pleft_4);
      playerSprite.add(pleft_5);
      playerSprite.add(pleft_6);
      playerSprite.add(pleft_7);
      playerSprite.add(pleft_8);
      playerSprite.add(pleft_9);
      frogSprite_1.add(frog1_a);
      frogSprite_1.add(frog1_b);
      frogSprite_2.add(frog2_a);
      frogSprite_2.add(frog2_b);
      bunnySprite_1.add(bunny1_a);
      bunnySprite_1.add(bunny1_b);
      bunnySprite_1.add(bunny1_c);
      bunnySprite_2.add(bunny2_a);
      bunnySprite_2.add(bunny2_b);
      bunnySprite_2.add(bunny2_c);
      pumaSprite.add(puma1);
      pumaSprite.add(puma2);
      pumaSprite.add(puma3);
      pumaSprite.add(puma4);
      pumaSprite.add(puma5);
      pumaSprite.add(puma6);
      pumaSprite.add(puma7);
      pumaSprite.add(puma8);
      piggySprite.add(piggy1);
      piggySprite.add(piggy2);
      piggySprite.add(piggy3);
      piggySprite.add(piggy4);
      birdSprite.add(bird1);
      birdSprite.add(bird2);
      birdSprite.add(bird3);
   }
}
